name: Create and Upload Build on Firebase.

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  build-and-distribute:
    name: Run Build
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    env:
      FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
      FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.13'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Deploy
        run:
          ./gradlew assembleDebug appDistributionUploadDebug